{% set name = 'psana' %}
{% set version = '4.0.51' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pswww.slac.stanford.edu/swdoc/tutorials/{{ name }}-conda-{{ version }}.tar.gz
  sha256: 2027d629d8d9d466d6b8ef8b5449c4f73f3473671516945a08a49ee1490ff537
  patches:
    - ndarray_ext.patch
    - header.patch
    - sysroot.patch

build:
  skip: True  # [win or osx]
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}
    - {{ cdt('mesa-dri-drivers') }}
    - {{ cdt('libselinux') }}
    - {{ cdt('libxdamage') }}
    - {{ cdt('libxxf86vm') }}
    - {{ cdt('libxext') }}
    - make
    - patch
  host:
    - python=3.9
    - scons
    - boost-cpp
    - boost
    - cython
    - xorg-libxfixes
    - qt
    - matplotlib-base
    - ndarray-psana=1.1.11
    - hdf5
    - curl
    - libcurl
    - libtiff
    - libpng
    - libuuid
    - six
    - zlib
  run:
    - python=3.9
    - qt
    - numpy
    - matplotlib-base
    - scipy
    - pyzmq
    - hdf5
    - h5py
    - _openmp_mutex
    - ndarray-psana=1.1.11
    - pytables
    - six
    - curl
    - libcurl 
    - libtiff
    - libpng
    - libuuid
    - six
    - zlib
    - {{ pin_compatible('boost') }}
    - {{ pin_compatible('boost-cpp') }}

test:
  commands:
    - psana -h

about:
  home: https://lcls.slac.stanford.edu
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: 'Data analysis softweare for the Linac Coherent Light Source'
  description: |
    psana is software that can be used to analyze LCLS data. Using
    relatively simple python code, it is possible to analyze LCLS data
    in parallel on hundreds of CPU cores, both offline and in real-time
    while data is being taken.
  doc_url: https://confluence.slac.stanford.edu/display/PSDM/LCLS+Data+Analysis
  dev_url: https://github.com/slaclab/anarel-manage  #Is this correct?

extra:
  recipe-maintainers:
    - valmar
    - chrisvam
