{% set name = 'psana' %}
{% set version = '4.0.24' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pswww.slac.stanford.edu/swdoc/tutorials/{{ name }}-conda-{{ version }}.tar.gz
  sha256: 5670b7ba3ad71790b703c44546b8a93a1442ddee14a8792a72fb3a813b7753c5 
  patches:
    - ndarray_ext.patch

build:
  skip: True  # [win or osx]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}
    - {{ cdt('mesa-dri-drivers') }}
    - {{ cdt('libselinux') }}
    - {{ cdt('libxdamage') }}
    - {{ cdt('libxxf86vm') }}
    - {{ cdt('libxext') }}
    - make
    - patch
  host:
    - python
    - scons
    - boost-cpp
    - boost
    - cython
    - xorg-libxfixes
    - qt
    - matplotlib-base
    - ndarray-psana
    - hdf5
    - curl
    - libcurl
    - libtiff
    - libpng
    - libuuid
    - six
    - zlib
  run:
    - python
    - qt
    - numpy
    - matplotlib-base
    - scipy
    - pyzmq
    - hdf5
    - h5py
    - _openmp_mutex
    - ndarray-psana
    - pytables
    - six
    - curl
    - libcurl 
    - libtiff
    - libpng
    - libuuid
    - six
    - zlib
    - {{ pin_compatible('boost') }}
    - {{ pin_compatible('boost-cpp') }}

test:
  commands:
    - psana -h

about:
  home: https://lcls.slac.stanford.edu
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: 'Data analysis softweare for the Linac Coherent Light Source'
  description: |
    psana is software that can be used to analyze LCLS data. Using
    relatively simple python code, it is possible to analyze LCLS data
    in parallel on hundreds of CPU cores, both offline and in real-time
    while data is being taken.
  doc_url: https://confluence.slac.stanford.edu/display/PSDM/LCLS+Data+Analysis
  dev_url: https://github.com/slaclab/anarel-manage  #Is this correct?

extra:
  recipe-maintainers:
    - valmar
    - chrisvam
