{% set name = 'psana' %}
{% set version = '4.0.62' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
#  url: https://pswww.slac.stanford.edu/swdoc/tutorials/{{ name }}-conda-{{ version }}.tar.gz
#  url: https://s3df.slac.stanford.edu/people/psreldev/{{ name }}-conda-{{ version }}.tar.gz  # WARNING: Error: HTTP 403 FORBIDDEN for url
#  url: file:///sdf/group/lcls/ds/ana/sw/conda1-v3/manage/downloads/anarel/psana-conda-4.0.62.tar.gz
  url: file:///sdf/group/lcls/ds/ana/sw/conda1-v3/manage/downloads/anarel/{{ name }}-conda-{{ version }}.tar.gz
  sha256: 489f3a43ee6177ee3ed73c7507b4bc837a6301e6a1bafe8f2193af332fec5088

patches:
    - sysroot.patch
#    - ndarray_ext.patch
#    - header.patch

build:
  skip: True  # [win or osx]
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}
    - {{ cdt('mesa-dri-drivers') }}
    - {{ cdt('libselinux') }}
    - {{ cdt('libxdamage') }}
    - {{ cdt('libxxf86vm') }}
    - {{ cdt('libxext') }}
    - make
    - patch
  host:
    - python=3.9
    - scons
    - boost-cpp
    - boost
    - cython
    - xorg-libxfixes
    - qt
    - matplotlib-base
    - ndarray-psana=1.1.11
    - hdf5
    - curl
    - libcurl
    - libtiff
    - libpng
    - libuuid
    - six
    - zlib
  run:
    - python=3.9
    - qt
    - pyqt
    - numpy
    - matplotlib-base
    - scipy
    - pyzmq
    - hdf5
    - h5py
    - _openmp_mutex
    - ndarray-psana=1.1.11
    - pytables
    - six
    - curl
    - libcurl 
    - libpng
    - libuuid
    - six
    - zlib
    - {{ pin_compatible('boost') }}
    - {{ pin_compatible('boost-cpp') }}
    - {{ pin_compatible('libtiff') }}

test:
  files:
    - test_sample.py
  source_files:
    - Detector/test/pytest_detector.py
    - Detector/test/unittest_detector
  requires:
    - pytest
  commands:
    - psana -h
    - pytest test_sample.py
    - pytest Detector/test/pytest_detector.py
    - python Detector/test/unittest_detector

about:
  home: https://lcls.slac.stanford.edu
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: 'Data analysis softweare for the Linac Coherent Light Source'
  description: |
    psana is software that can be used to analyze LCLS data. Using
    relatively simple python code, it is possible to analyze LCLS data
    in parallel on hundreds of CPU cores, both offline and in real-time
    while data is being taken.
  doc_url: https://confluence.slac.stanford.edu/display/PSDM/LCLS+Data+Analysis
  dev_url: https://github.com/slaclab/anarel-manage  #Is this correct?

extra:
  recipe-maintainers:
    - valmar
    - chrisvam
    - dubrovin
