recipe_dir: recipe
skip_render:
  - README.md
  - LICENSE.txt
  - .gitattributes
  - .gitignore
  - build-locally.py
  - LICENSE
  - .github/CONTRIBUTING.md
  - .github/ISSUE_TEMPLATE.md
  - .github/PULL_REQUEST_TEMPLATE.md
  - .github/workflows
azure:
  store_build_artifacts: True
channels:
  sources:
    - valmar
    - conda-forge
    - defaults
  targets:
    - ["valmar", "psana"]
